default:
    - api_key: "sk-4177a6705d084829b148e96cfef6ed15"
      organization: "deepseek"

deepseek-chat:
    - client_class: "openai.OpenAI"
      api_key: "sk-4177a6705d084829b148e96cfef6ed15"
      endpoint: "<your DeepSeek API endpoint here>"